# docker-compose.deploy.yml
version: '3.8'

networks:
  micro_network:
    external:
      name: micro_network

services:
  user-api:
    container_name: user-svc
    build:
      context: ../user-service
    ports:
    - "5001:5001"
    depends_on:
      - user-db
    networks:
      - micro_network
    restart: always

  product-api:
    container_name: product-svc
    build:
      context: ../product-service
    ports:
    - "5002:5002"
    depends_on:
      - product-db
    networks:
      - micro_network
    restart: always


  order-api:
    container_name: order-svc
    build:
      context: ../order-service
    ports:
    - "5003:5003"
    depends_on:
      - order-db
    networks:
      - micro_network
    restart: always

  # db:
  #   container_name: mysql-svc
  #   image: mysql:8
  #   ports:
  #   - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: pfm_dc_2020
  #     MYSQL_USER: cloudacademy
  #     MYSQL_PASSWORD: pfm_2020
  #   networks:
  #     - micro_network
  #   volumes:
  #     - ../data:/var/lib/mysql
  #     - ../initdb:/docker-entrypoint-initdb.d

  frontend-app:
    container_name: frontend-svc
    build:
      context: .
    ports:
    - "5000:5000"
    networks:
      - micro_network
    restart: always